

# Choices for Exterior Model
MODEL_EX_CHOICES = [("Factory New", "Factory New"),
                    ("Minimal Wear", "Minimal Wear"),
                    ("Field-Tested", "Field-Tested"),
                    ("Well-Worn", "Well-Worn"),
                    ("Battle-Scarred", "Battle-Scarred")]

MODEL_GT_CHOICES = [("CZ75-Auto", "CZ75-Auto"),
                    ("Desert Eagle", "Desert Eagle"),
                    ("Dual Berettas", "Dual Berettas"),
                    ("Five-SeveN", "Five-SeveN"),
                    ("Glock-18","Glock-18"),
                    ("P2000", "P2000"),
                    ("P250", "P250"),
                    ("R8 Revolver", "R8 Revolver"),
                    ("Tec-9", "Tec-9"),
                    ("USP-S", "USP-S"),
                    ("MAG-7", "MAG-7"),
                    ("Nova", "Nova"),
                    ("Sawed-Off", "Sawed-Off"),
                    ("XM1014", "XM1014"),
                    ("M249", "M249"),
                    ("Negev", "Negev"),
                    ("MAC-10", "MAC-10"),
                    ("MP5-SD", "MP5-SD"),
                    ("MP7", "MP7"),
                    ("MP9", "MP9"),
                    ("P90", "P90"),
                    ("PP-Bizon", "PP-Bizon"),
                    ("UMP-45", "UMP-45"),
                    ("AK-47", "AK-47"),
                    ("AUG", "AUG"),
                    ("FAMAS", "FAMAS"),
                    ("Galil AR", "Galil AR"),
                    ("M4A1-S", "M4A1-S"),
                    ("M4A4", "M4A4"),
                    ("SG 553", "SG 553"),
                    ("AWP", "AWP"),
                    ("G3SG1", "G3SG1"),
                    ("SCAR-20", "SCAR-20"),
                    ("SSG 08", "SSG 08")]

MODEL_WT_CHOICES = [("Pistols", "Pistols"),
                    ("Heavy", "Heavy"),
                    ("Rifle", "Rifle"),
                    ("SMG", "SMG"),
                    ("Knife", "Knife")]

MODEL_KN_CHOICES = [("Bayonet", "Bayonet"),
                    ("Bowie Knife", "Bowie Knife"),
                    ("Butterfly Knife", "Butterfly Knife"),
                    ("Classic Knife", "Classic Knife"),
                    ("Falchion Knife", "Falchion Knife"),
                    ("Flip Knife", "Flip Knife"),
                    ("Gut Knife", "Gut Knife"),
                    ("Huntsman Knife", "Huntsman Knife"),
                    ("Karambit", "Karambit"),
                    ("M9 Bayonet", "M9 Bayonet"),
                    ("Navaja Knife", "Navaja Knife"),
                    ("Nomad Knife", "Nomad Knife"),
                    ("Paracord Knife", "Paracord Knife"),
                    ("Shadow Daggers", "Shadow Daggers"),
                    ("Skeleton Knife", "Skeleteon Knife"),
                    ("Stiletto Knife", "Stiletto Knife"),
                    ("Survival Knife", "Survival Knife"),
                    ("Talon Knife", "Talon Knife"),
                    ("Ursus Knife", "Ursus Knife")]

EX_CHOICES = ['Factory New',
              'Minimal Wear',
              'Field-Tested',
              'Well-Worn',
              'Battle-Scarred']

GT_CHOICES = ['CZ75-Auto',
              'Desert Eagle',
              'Dual Berettas',
              'Five-SeveN',
              'Glock-18',
              'P2000',
              'P250',
              'R8 Revolver',
              'Tec-9',
              'USP-S',
              'MAG-7',
              'Nova',
              'Sawed-Off',
              'XM1014',
              'M249',
              'Negev',
              'MAC-10',
              'MP5-SD',
              'MP7',
              'MP9',
              'P90',
              'PP-Bizon',
              'UMP-45',
              'AK-47',
              'AUG',
              'FAMAS',
              'Galil AR',
              'M4A1-S',
              'M4A4',
              'SG 553',
              'AWP',
              'G3SG1',
              'SCAR-20',
              'SSG 08']

WT_CHOICES = ['Pistols',
              'Heavy',
              'Rifle',
              'SMG',
              'Knife']

KN_CHOICES = ['Bayonet',
              'Bowie Knife',
              'Butterfly Knife',
              'Classic Knife',
              'Falchion Knife',
              'Flip Knife',
              'Gut Knife',
              'Huntsman Knife',
              'Karambit',
              'M9 Bayonet',
              'Navaja Knife',
              'Nomad Knife',
              'Paracord Knife',
              'Shadow Daggers',
              'Skeleton Knife',
              'Stiletto Knife',
              'Survival Knife',
              'Talon Knife',
              'Ursus Knife']
