# Generated by Django 4.0.3 on 2022-03-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GloveSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('rarity', models.CharField(max_length=20)),
                ('rarity_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GunSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('weapon_type', models.CharField(max_length=20)),
                ('gun_type', models.CharField(max_length=30)),
                ('exterior', models.CharField(max_length=30)),
                ('rarity', models.CharField(max_length=20)),
                ('rarity_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KnifeSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('weapon_type', models.CharField(max_length=10)),
                ('knife_type', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('rarity_color', models.CharField(max_length=10)),
            ],
        ),
    ]
