# Generated by Django 4.0.3 on 2022-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunskin',
            name='souvenir',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gunskin',
            name='tournament',
            field=models.CharField(default='', max_length=100),
        ),
    ]
