# Generated by Django 4.0.3 on 2022-03-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0002_gunskin_souvenir_gunskin_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gloveskin',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gunskin',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='knifeskin',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listid', models.BigIntegerField()),
                ('gloves', models.ManyToManyField(to='skin_details.gloveskin')),
                ('guns', models.ManyToManyField(to='skin_details.gunskin')),
                ('knives', models.ManyToManyField(to='skin_details.knifeskin')),
            ],
        ),
    ]
