# Generated by Django 4.0.3 on 2022-03-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0003_alter_gloveskin_options_alter_gunskin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='gloves',
            field=models.ManyToManyField(blank=True, to='skin_details.gloveskin'),
        ),
        migrations.AlterField(
            model_name='list',
            name='guns',
            field=models.ManyToManyField(blank=True, to='skin_details.gunskin'),
        ),
        migrations.AlterField(
            model_name='list',
            name='knives',
            field=models.ManyToManyField(blank=True, to='skin_details.knifeskin'),
        ),
    ]
