# Generated by Django 4.0.3 on 2022-03-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0004_alter_list_gloves_alter_list_guns_alter_list_knives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='SavedList',
        ),
    ]
