# Generated by Django 4.0.3 on 2022-03-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0006_alter_savedlist_listid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlist',
            name='listid',
        ),
    ]
