# Generated by Django 4.1.1 on 2022-09-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0007_remove_savedlist_listid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloveskin',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='gloveskin',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gunskin',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='gunskin',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='gunskin',
            name='type',
        ),
        migrations.RemoveField(
            model_name='knifeskin',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='knifeskin',
            name='type',
        ),
        migrations.AddField(
            model_name='gloveskin',
            name='exterior',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gloveskin',
            name='icon_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gloveskin',
            name='icon_url_large',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunskin',
            name='icon_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunskin',
            name='icon_url_large',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunskin',
            name='stattrak',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knifeskin',
            name='exterior',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knifeskin',
            name='icon_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knifeskin',
            name='icon_url_large',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knifeskin',
            name='stattrak',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
