# Generated by Django 4.1.1 on 2022-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0008_remove_gloveskin_classid_remove_gloveskin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloveskin',
            name='icon_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='gloveskin',
            name='icon_url_large',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='gloveskin',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='icon_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='icon_url_large',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='icon_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='icon_url_large',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
