# Generated by Django 4.1.1 on 2022-09-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0009_alter_gloveskin_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunskin',
            name='gun_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='icon_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='icon_url_large',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='weapon_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
