# Generated by Django 4.1.1 on 2022-10-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0010_alter_gunskin_gun_type_alter_gunskin_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunskin',
            name='exterior',
            field=models.CharField(choices=[('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='souvenir',
            field=models.BigIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='stattrak',
            field=models.BigIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
