# Generated by Django 4.1.1 on 2022-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0011_alter_gunskin_exterior_alter_gunskin_souvenir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunskin',
            name='gun_type',
            field=models.CharField(choices=[('CZ75-Auto', 'CZ75-Auto'), ('Desert Eagle', 'Desert Eagle'), ('Dual Berettas', 'Dual Berettas'), ('Five-SeveN', 'Five-SeveN'), ('Glock-18', 'Glock-18'), ('P2000', 'P2000'), ('P250', 'P250'), ('R8 Revolver', 'R8 Revolver'), ('Tec-9', 'Tec-9'), ('USP-S', 'USP-S'), ('MAG-7', 'MAG-7'), ('Nova', 'Nova'), ('Sawed-Off', 'Sawed-Off'), ('XM1014', 'XM1014'), ('M249', 'M249'), ('Negev', 'Negev'), ('MAC-10', 'MAC-10'), ('MP5-SD', 'MP5-SD'), ('MP7', 'MP7'), ('MP9', 'MP9'), ('P90', 'P90'), ('PP-Bizon', 'PP-Bizon'), ('UMP-45', 'UMP-45'), ('AK-47', 'AK-47'), ('AUG', 'AUG'), ('FAMAS', 'FAMAS'), ('Galil AR', 'Galil AR'), ('M4A1-S', 'M4A1-S'), ('M4A4', 'M4A4'), ('SG 553', 'SG 553'), ('AWP', 'AWP'), ('G3SG1', 'G3SG1'), ('SCAR-20', 'SCAR-20'), ('SSG 08', 'SSG 08')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistols', 'Pistols'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='exterior',
            field=models.CharField(choices=[('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], max_length=30),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='stattrak',
            field=models.BigIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistols', 'Pistols'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife')], max_length=10),
        ),
    ]
