# Generated by Django 4.1.1 on 2022-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0013_alter_gloveskin_exterior_alter_gunskin_souvenir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knifeskin',
            name='rarity_color',
        ),
        migrations.AlterField(
            model_name='gloveskin',
            name='exterior',
            field=models.CharField(choices=[('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], max_length=30),
        ),
    ]
