# Generated by Django 4.1.1 on 2022-10-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0015_gunskin_souvenir_gunskin_stattrak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knifeskin',
            name='knife_type',
            field=models.CharField(choices=[('Bayonet', 'Bayonet'), ('Bowie Knife', 'Bowie Knife'), ('Butterfly Knife', 'Butterfly Knife'), ('Classic Knife', 'Classic Knife'), ('Falchion Knife', 'Falchion Knife'), ('Flip Knife', 'Flip Knife'), ('Gut Knife', 'Gut Knife'), ('Huntsman Knife', 'Huntsman Knife'), ('Karambit', 'Karambit'), ('M9 Bayonet', 'M9 Bayonet'), ('Navaja Knife', 'Navaja Knife'), ('Nomad Knife', 'Nomad Knife'), ('Paracord Knife', 'Paracord Knife'), ('Shadow Daggers', 'Shadow Daggers'), ('Skeleton Knife', 'Skeleteon Knife'), ('Stiletto Knife', 'Stiletto Knife'), ('Survival Knife', 'Survival Knife'), ('Talon Knife', 'Talon Knife'), ('Ursus Knife', 'Ursus Knife')], max_length=20),
        ),
    ]
