# Generated by Django 4.1.1 on 2022-10-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0016_alter_knifeskin_knife_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife')], max_length=10),
        ),
    ]
