# Generated by Django 4.1.1 on 2022-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_details', '0017_alter_gunskin_weapon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloveskin',
            name='generic',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife'), ('Gloves', 'Gloves')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='gloveskin',
            name='glove_type',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunskin',
            name='generic',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife'), ('Gloves', 'Gloves')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='knifeskin',
            name='generic',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife'), ('Gloves', 'Gloves')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gunskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife'), ('Gloves', 'Gloves')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='knifeskin',
            name='weapon_type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Heavy', 'Heavy'), ('Rifle', 'Rifle'), ('SMG', 'SMG'), ('Knife', 'Knife'), ('Gloves', 'Gloves')], max_length=10),
        ),
    ]
